# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - pylava
          - checkdoc
          - mypy

    steps:

      - uses: actions/checkout@v2

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install tox
        run: python -m pip install tox

      - name: Prepare tox env
        run: tox --notest
        env:
          TOXENV: ${{ matrix.linter }}

      - name: Run ${{ matrix.linter }}
        run: tox
        env:
          FORCE_COLOR: yes
          TOXENV: ${{ matrix.linter }}

  tests:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - python: '3.7'
            toxenv: py37
          - python: '3.8'
            toxenv: py38
          - python: '3.9'
            toxenv: py39
          - python: '3.10'
            toxenv: py310

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: python -m pip install tox

      - name: Prepare tox env
        run: tox --notest
        env:
          TOXENV: ${{ matrix.toxenv }}

      - name: Run tox
        run: tox
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: yes
          TOXENV: ${{ matrix.toxenv }}
